default_language_version:
  python: python3.7
default_stages: [commit, push, manual]
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: black
      entry: black
      language_version: python3.7
      require_serial: true
      types: [python]
      files: \.pyi?$

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.0.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language: python
        language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: check-yaml
      language: python
    - id: check-added-large-files
      language: python
    - id: fix-encoding-pragma
      language: python
    # - id: name-tests-test
    #   language: python
    - id: check-docstring-first
      language: python
    - id: flake8
      language: python
    - id: end-of-file-fixer
      language: python
    - id: trailing-whitespace
      language: python
      types: [text]
    - id: debug-statements
      name: Debug Statements (Python)
      description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
      entry: debug-statement-hook
      language: python
      types: [python]


-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    - id: reorder-python-imports
      name: Reorder python imports
      description: This hook reorders imports in python files.
      entry: reorder-python-imports
      language: python
      types: [python]
      minimum_pre_commit_version: "0.15.0"

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
    - id: clang-format
      name: clang-format
      entry: hooks/clang-format
      description: Formats C/CPP code
      files: "\\.(c|cc|cxx|cpp|h|hpp|hxx|m)$"
      language: script
      additional_dependencies: [clang-format]
      args: [--style=Google, -i]

#     - id: clang-tidy
#       name: clang-tidy
#       entry: hooks/clang-tidy
#       description: Find warnings/errors in C/CPP code
#       files: "\\.(c|cc|cxx|cpp|h|hpp|hxx|m)$"
#       language: script
#       additional_dependencies: [clang-tidy]
#       args: [-checks=*, -warnings-as-errors=*]

    # - id: oclint
    #   name: oclint
    #   entry: hooks/oclint
    #   description: Find warnings/errors in C/CPP code
    #   files: "\\.(c|cc|cxx|cpp|h|hpp|hxx|m)$"
    #   language: script
    #   additional_dependencies: [oclint]
    #   args: [-enable-clang-static-analyzer, -enable-global-analysis]
