name: mrsimulator-dev
channels:
  - anaconda
  - conda-forge
dependencies:
  - fftw>=3.3.9
  - openblas>=0.3.19
  - numpy>=1.17
  - nomkl
  - setuptools>=27.3
  - cython>=0.29
  - matplotlib>=3.3.4
  - pandas>=1.1.3
  - pip
  - pip:
      - monty>=2.0.4
      - csdmpy>=0.4.1
      - pydantic>=1.9
      - typing-extensions>=3.7
      - flake8
      - lmfit>=1.0.2
      - psutil>=5.4.8
      - joblib>=1.0.0
      # for testing
      - pytest
      - pytest-cov
      - sympy
      # building docs
      - sphinx>=2.0
      - sphinxjp.themes.basicstrap
      - sphinx-copybutton>=0.2.12
      - sphinx-gallery>=0.10
      - pillow>=7.1.2
      - breathe==4.26
      - sphinx-tabs>=1.1.13
      - recommonmark
      - sphinx-version-warning
