name: mrsimulator-dev
channels:
  - anaconda
  - conda-forge
dependencies:
  - fftw>=3.3.9
  - openblas
  - numpy>=1.20
  - nomkl
  - setuptools>=27.3
  - cython>=0.29
  - matplotlib>=3.3.4
  - pandas>=1.1.3
  - pip
  - pip:
      - monty>=2.0.4
      - csdmpy>=0.6.dev2
      - astropy>=3.0
      - pydantic<2
      - typing-extensions>=3.7
      - lmfit>=1.0.2
      - psutil>=5.4.8
      - joblib>=1.0.0
      # building docs
      - sphinx>=2.0
      - sphinxjp.themes.basicstrap
      - sphinx-copybutton>=0.2.12
      - sphinx-gallery>=0.10
      - pillow>=7.1.2
      - breathe==4.26
      - sphinx-tabs>=1.1.13
      - recommonmark
      - sphinx-version-warning
      - nmrglue>=0.9
