name: mrsimulator-dev
channels:
  - anaconda
dependencies:
  - fftw>=3.3.0
  - openblas
  - numpy>=1.16
  - setuptools>=27.3
  - cython>=0.29
  - matplotlib>=3.0
  - pip
  - pip:
      - monty>=2.0.4
      - csdmpy>=0.2.1
      - pydantic>=1.0
      - flake8
      # for testing
      - pytest
      - pytest-cov
      - sympy
      - lmfit>=1.0.0
      # building docs
      - sphinx>=2.0
      - sphinxjp.themes.basicstrap
      - sphinx-copybutton>=0.2.11
      - sphinx-gallery>0.6.2
      - pillow>=7.1.2
      - breathe>=4.18
      - sphinx-tabs>=1.1.13
